ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS price_tier_2 NUMERIC(12,2);
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS price_tier_3 NUMERIC(12,2);

ALTER TABLE order_lines ADD COLUMN IF NOT EXISTS vehicle_tier INTEGER;
